### ISSUE TITLE
Obtaining an institution ID

### ISSUE THREAD

**Issue by RobertPincus** [PCMDI/input4MIPs-cmor-tables#1]
Hello - 

As part of the Radiative Forcing MIP (RFMIP) I would like to post input data on input4MIPs. For this I will need to specify, among other things, an "institution" and an "institution_id". My institution is the University of Colorado; if one needed more specificity it could be CIRES or the Cooperative Institute for Research in Environmental Sciences with the University. 

How do obtain a formal institution name and institution_id? 

- Robert Pincus
Robert.Pincus@colorado.edu

**Comment by durack1** [comment]
@RobertPincus are you planning on using [CMOR3](https://github.com/PCMDI/cmor) to write your data? If so we will have to reorganize this repo to facilitate institution registrations.

@taylor13 pinging you here

**Comment by RobertPincus** [comment]
@durack1 No I am not planning to use CMOR3. I've been working with @taylor13 on this file, which will be used as part of RFMIP. It'll be CF-compliant but doesn't need the full CMOR treatment. 

I've been told the institution_id is required but don't have ideas about how to get one. I don't imagine I'm the only person with this question.

**Comment by durack1** [comment]
@RobertPincus at this stage for the input4MIPs project there is no need to register an `institution_id`, rather you can generate your own and use this in contributed netcdf CF-compliant files. For an example, with PCMDI data contributed to input4MIPs (AMIP boundary conditions) we have used the `institution_id`:
```
"PCMDI":"Program for Climate Model Diagnosis and Intercomparison, Lawrence Livermore National Laboratory, Livermore, CA 94550, USA"
```
Other contributors to input4MIPs currently include: `PCMDI, PNNL-JGCRI, UReading, UoM, and VUA` (see these [here](https://pcmdi.llnl.gov/search/input4mips/))

There is a detailed example of the file netcdf file contents and global attributes (an ncdump output) [here](https://docs.google.com/document/d/1pU9IiJvPJwRvIgVaSDdJ4O0Jeorv_2ekEtted34K9cA/edit#heading=h.cn9f7982ycw6)

**Comment by RobertPincus** [comment]
@durack1 OK, I'll wing it on the institution_id. Thanks for the links; those are helpful.

**Comment by durack1** [comment]
@RobertPincus no problem, let me know if you need any feedback on the files you're developing
