### ISSUE TITLE
Register institution_id for NASA-GSFC

### ISSUE THREAD

**Issue by geresie** [PCMDI/input4MIPs-cmor-tables#101]
label = NASA-GSFC-ACCESS1-3-rcp85-1-0
source_id = NASA-GSFC-ACCESS1-3-rcp85-1-0
institution_id = NASA-GSFC
release_year = 2020
activity_participation = ISMIP6

**Comment by durack1** [comment]
@geresie just getting to this, I'm a little concerned with a 29 character source_id which I presume will then set the template for the remainder of the contributions. I think this is a bit long, for the CMIP6 model/source_id's we've limited this to 16 characters.

You will have the **institution_id** included in the directory listing, following the template examples below (using PCMDI) and linked [here](https://docs.google.com/document/d/1pU9IiJvPJwRvIgVaSDdJ4O0Jeorv_2ekEtted34K9cA/edit#heading=h.cn9f7982ycw6):
```
Proposed directory structure for input4MIPs:
input4MIPs/<mip_era>/<target_mip>/<institution_id>/<source_id>/<realm>/<frequency>/
<variable_id>/<grid_label>/<version>/files.nc

Directory e.g.
input4MIPs/CMIP6/CMIP/PCMDI/PCMDI-AMIP-1-1-6/ocean/mon/tos/gn/v20191121/

Proposed filename for input4MIPs:
<variable_id>_input4MIPs_<dataset_category>_<target_mip>_<source_id>_
<grid_label>[_<time_range>].nc
In the case when there are multiple variables in a file and the “multiple”
variable_id is being used, to prevent filename clashes, an additional
<variable_id>-[multiple_file_indentifier] can be appended.

File e.g.
tos_input4MIPs_SSTsAndSeaIce_CMIP_PCMDI-AMIP-1-1-6_gn_187001-201812.nc
```

As an example of what we are recording for input4MIPs, which differs with what we are recording for **models/source_id's contributing to CMIP6**, here is the entry for the latest release of the PCMDI AMIP boundary condition data, you can view registered input4MIPs source_id entries in [PCMDI/input4MIPs-cmor-tables/input4MIPs_source_id.json](https://github.com/PCMDI/input4MIPs-cmor-tables/blob/master/input4MIPs_source_id.json). I note you don't have to fill out all these details, we have, as we know them. For an earlier version, we have far fewer registered details, see [PCMDI-AMIP-1-1-3](https://github.com/PCMDI/input4MIPs-cmor-tables/blob/master/input4MIPs_source_id.json#L90-L92):
```
        "PCMDI-AMIP-1-1-6":{
            "comment":"Based on Hurrell SST/sea ice consistency criteria applied to merged HadISST (1870-01 to 1981-10) & NCEP-0I2 (1981-11 to 2018-12)",
            "contact":"PCMDI (pcmdi-cmip@llnl.gov)",
            "dataset_category":"SSTsAndSeaIce",
            "further_info_url":"https://pcmdi.llnl.gov/mips/amip",
            "grid":"1x1 degree longitude x latitude",
            "grid_label":"gn",
            "institution":"Program for Climate Model Diagnosis and Intercomparison, Lawrence Livermore National Laboratory, Livermore, CA 94550, USA",
            "institution_id":"PCMDI",
            "nominal_resolution":"1x1 degree",
            "product":"observations",
            "references":"Taylor, K.E., D. Williamson and F. Zwiers, 2000: The sea surface temperature and sea ice concentration boundary conditions for AMIP II simulations. PCMDI Report 60, Program for Climate Model Diagnosis and Intercomparison, Lawrence Livermore National Laboratory, 25 pp. Available online: https://pcmdi.llnl.gov/report/pdf/60.pdf",
            "region":[
                "global_ocean"
            ],
            "release_year":"2019",
            "source":"PCMDI-AMIP 1.1.6: Merged SST based on UK MetOffice HadISST and NCEP OI2",
            "source_description":"Sea surface temperature and sea-ice datasets produced by PCMDI (LLNL) for the AMIP (DECK) experiment of CMIP6",
            "source_id":"PCMDI-AMIP-1-1-6",
            "source_type":"satellite_blended",
            "source_variables":[
                "areacello",
                "sftof",
                "siconc",
                "siconcbcs",
                "tos",
                "tosbcs"
            ],
            "source_version":"1.1.6",
            "target_mip":"CMIP",
            "title":"PCMDI-AMIP 1.1.6 dataset prepared for input4MIPs"
        },
```
The advantage of provide this information, is that CMOR (if it's used) will write all these details into each of your files. So if there is a subsequent data release, you can just update your registered detail, so e.g. NASA-GFSC-ISMIP6-1-0 to NASA-GFSC-ISMIP6-1-1, update information associated with the new 1.1 vs 1.0 release and voila

**Comment by geresie** [comment]
Please see revised source_id without the institution_id in the name and with more content. We put as much content in it as it made sense to still keep it flexible.

"ACCESS1-3-rcp85-1-0":{
            "comment":"This dataset was prepared using CMIP5 model ACCESS1-3 as input. A combination of historical and rcp85 datasets were used to create this forcing dataset for ISMIP6.",
            "contact":"ismip6@gmail.com",            
	    "further_info_url":"http://www.climate-cryosphere.org/wiki/index.php?title=ISMIP6_wiki_page",
            "institution":"NASA GSFC, 8800 Greenbelt Rd, Greenbelt, MD 20771, USA",
            "institution_id":"NASA-GSFC",
            "product":"derived",
            "references":"Experimental protocol for sealevel projections from ISMIP6 standalone ice sheet models, S. Nowicki et al, 2020, https://doi.org/10.5194/tc-2019-322",
            "release_year":"2020",
            "source":"ACCESS1-3-rcp85-1-0 derived dataset computed from CMIP5 ACCESS1-3-rcp85 and historical simulations",
            "source_description":"Ice sheet relevant datasets produced by ISMIP6 Team for the standalone ice sheet experiment of ISMIP6",
            "source_id":"ACCESS1-3-rcp85-1-0”,
            "source_type":"AOGCM",
	    "source_version":"1.0",
            "target_mip":"ISMIP6",
            "title":"Dataset derived from ACCESS1-3-rcp85-1-0 prepared for ISMIP6 (CMIP6)"
        },

please let me know what you think. We have 17 more source_ids to register after this. Thanks

**Comment by durack1** [comment]
@geresie apologies for dragging on this. Just to clarify, you are using CMOR3 to write your data? I ask this, as the information above will be written to files if you use a CMOR3 recipe, similar to how we do this for the PCMDI AMIP data

**Comment by geresie** [comment]
Thanks for getting back to me. Yes, I am using CMOR3 to write the data.
I have another question just to clarify the process. 
Would it be acceptable to put in a separate registration as an issue for each source_id we are planning to register or to put in 1 issue for all the source_ids?
Thanks

**Comment by durack1** [comment]
@geresie good question, just one issue would be fine, this is all hand-spun anyway.

As much of the information is duplicated, it might be useful to indicate the `source_id` and custom info associated with each, and then the generic information reproduced for each entry. That way I save you a copy as paste job on your side, and mine too. So from a quick scan above, `source_id`, `comment`, `source` and `title` will need to be amended, and to be honest these are standard templates too, just with the ..`source_id`.. entry customized. So that simplifies things considerably.

So just provide the source_id's and I can harvest the info above.

**Comment by geresie** [comment]
Thanks so much  Paul.
Here are all the source_ids:
ACCESS1-3-rcp85-1-0
CCSM4-rcp26-1-0
CCSM4-rcp85-1-0
CESM2-ssp585-1-0
CNRM-CM6-1-ssp126-1-0
CNRM-CM6-1-ssp585-1-0
CNRM-ESM2-1-ssp585-1-0
CSIRO-MK3-6-0-rcp85-1-0
HadGEM2-ES-rcp85-1-0
IPSL-CM5A-MR-rcp26-1-0
IPSL-CM5A-MR-rcp85-1-0
MIROC-ESM-CHEM-rcp26-1-0
MIROC-ESM-CHEM-rcp85-1-0
MIROC5-rcp26-1-0
MIROC5-rcp85-1-0
NorESM1-M-rcp26-1-0
NorESM1-M-rcp85-1-0
UKESM1-0-LL-ssp585-1-0

You are right that only the source_id, comment, source and title are different for each dataset. For the models derived from CMIP6 there will be changes to reflect that as you can see below.

Please see these below the specifics for each source_id:

CMIP5 derived models


ACCESS1-3-rcp85-1-0

"source_id":" ACCESS1-3-rcp85-1-0”,

"comment":"This dataset was prepared using CMIP5 model ACCESS1-3 as input. A combination of historical and rcp85 datasets were used to create this forcing dataset for ISMIP6.",

"source":" ACCESS1-3-rcp85-1-0 derived dataset computed from CMIP5 ACCESS1-3-rcp85 and historical simulations",

"title":" Dataset derived from ACCESS1-3-rcp85-1-0 prepared for ISMIP6 (CMIP6)."

CCSM4-rcp26-1-0

"source_id":" CCSM4-rcp26-1-0”,

"comment":"This dataset was prepared using CMIP5 model CCSM4 as input. A combination of historical and rcp26 datasets were used to create this forcing dataset for ISMIP6.",

"source":" CCSM4-rcp26-1-0
 derived dataset computed from CMIP5 CCSM4 rcp26 and historical simulations",
"title":"Dataset derived from CCSM4-rcp26-1-0 prepared for ISMIP6 (CMIP6)"

CCSM4-rcp85-1-0

"source_id":" CCSM4-rcp85-1-0”,

"comment":"This dataset was prepared using CMIP5 model CCSM4 as input. A combination of historical and rcp85 datasets were used to create this forcing dataset for ISMIP6.",

"source":" CCSM4-rcp85-1-0
 derived dataset computed from CMIP5 CCSM4 rcp85 and historical simulations",
"title":"Dataset derived from CCSM4-rcp85-1-0 prepared for ISMIP6 (CMIP6)"


CSIRO-MK3-6-0-rcp85-1-0

"source_id":" CSIRO-MK3-6-0-rcp85-1-0”,

"comment":"This dataset was prepared using CMIP5 model CSIRO-MK3-6-0 as input. A combination of historical and rcp85 datasets were used to create this forcing dataset for ISMIP6.",

"source":" CSIRO-MK3-6-0-rcp85-1-0
 derived dataset computed from CMIP5 CSIRO-MK3-6-0 rcp85 and historical simulations",
"title":"Dataset derived from CSIRO-MK3-6-0-rcp85-1-0
 prepared for ISMIP6 (CMIP6)"


HadGEM2-ES-rcp85-1-0

"source_id":" HadGEM2-ES-rcp85-1-0”,

"comment":"This dataset was prepared using CMIP5 model HadGEM2-ES as input. A combination of historical and rcp85 datasets were used to create this forcing dataset for ISMIP6.",

"source":" HadGEM2-ES-rcp85-1-0
 derived dataset computed from CMIP5 HadGEM2-ES  rcp85
and historical simulations",
"title":"Dataset derived from HadGEM2-ES-rcp85-1-0
 prepared for ISMIP6 (CMIP6)"


IPSL-CM5A-MR-rcp26-1-0

"source_id":" IPSL-CM5A-MR-rcp26-1-0”,

"comment":"This dataset was prepared using CMIP5 model IPSL-CM5A-MR as input. A combination of historical and rcp26 datasets were used to create this forcing dataset for ISMIP6.",

"source":" IPSL-CM5A-MR-rcp26-1-0

 derived dataset computed from CMIP5 IPSL-CM5A-MR rcp26
and historical simulations",
"title":"Dataset derived from IPSL-CM5A-MR-rcp26-1-0
 prepared for ISMIP6 (CMIP6)"


IPSL-CM5A-MR-rcp85-1-0

"source_id":" IPSL-CM5A-MR-rcp85-1-0”,

"comment":"This dataset was prepared using CMIP5 model IPSL-CM5A-MR as input. A combination of historical and rcp85 datasets were used to create this forcing dataset for ISMIP6.",

"source":" IPSL-CM5A-MR-rcp85-1-0

 derived dataset computed from CMIP5 IPSL-CM5A-MR rcp85
and historical simulations",
"title":"Dataset derived from IPSL-CM5A-MR-rcp85-1-0
 prepared for ISMIP6 (CMIP6)"


MIROC-ESM-CHEM-rcp26-1-0

"source_id":" MIROC-ESM-CHEM-rcp26-1-0”,

"comment":"This dataset was prepared using CMIP5 model MIROC-ESM-CHEM as input. A combination of historical and rcp26 datasets were used to create this forcing dataset for ISMIP6.",

"source":" MIROC-ESM-CHEM-rcp26-1-0

 derived dataset computed from CMIP5 MIROC-ESM-CHEM rcp26
and historical simulations",
"title":"Dataset derived from MIROC-ESM-CHEM-rcp26-1-0
 prepared for ISMIP6 (CMIP6)"


MIROC-ESM-CHEM-rcp85-1-0

"source_id":" MIROC-ESM-CHEM-rcp85-1-0”,

"comment":"This dataset was prepared using CMIP5 model MIROC-ESM-CHEM as input. A combination of historical and rcp85 datasets were used to create this forcing dataset for ISMIP6.",

"source":" MIROC-ESM-CHEM-rcp85-1-0

 derived dataset computed from CMIP5 MIROC-ESM-CHEM rcp85
and historical simulations",
"title":"Dataset derived from MIROC-ESM-CHEM-rcp85-1-0
 prepared for ISMIP6 (CMIP6)"




MIROC5-rcp26-1-0

"source_id":" MIROC5-rcp26-1-0”,

"comment":"This dataset was prepared using CMIP5 model MIROC5 as input. A combination of historical and rcp26 datasets were used to create this forcing dataset for ISMIP6.",

"source":" MIROC5-rcp26-1-0
derived dataset computed from CMIP5 MIROC5 rcp26
and historical simulations",
"title":"Dataset derived from MIROC5-rcp26-1-0
 prepared for ISMIP6 (CMIP6)"


MIROC5-rcp85-1-0

"source_id":" MIROC5-rcp85-1-0”,

"comment":"This dataset was prepared using CMIP5 model MIROC5 as input. A combination of historical and rcp85 datasets were used to create this forcing dataset for ISMIP6.",

"source":" MIROC5-rcp85-1-0
derived dataset computed from CMIP5 MIROC5 rcp85
and historical simulations",
"title":"Dataset derived from MIROC5-rcp85-1-0
 prepared for ISMIP6 (CMIP6)"


NorESM1-M-rcp26-1-0

"source_id":" NorESM1-M-rcp26-1-0”,

"comment":"This dataset was prepared using CMIP5 model NorESM1-M as input. A combination of historical and rcp26 datasets were used to create this forcing dataset for ISMIP6.",

"source":" NorESM1-M-rcp26-1-0
derived dataset computed from CMIP5 NorESM1-M rcp26
and historical simulations",
"title":"Dataset derived from NorESM1-M-rcp26-1-0

 prepared for ISMIP6 (CMIP6)"


NorESM1-M-rcp85-1-0

"source_id":" NorESM1-M-rcp85-1-0”,

"comment":"This dataset was prepared using CMIP5 model NorESM1-M as input. A combination of historical and rcp85 datasets were used to create this forcing dataset for ISMIP6.",

"source":" NorESM1-M-rcp85-1-0
derived dataset computed from CMIP5 NorESM1-M rcp85
and historical simulations",
"title":"Dataset derived from NorESM1-M-rcp85-1-0 prepared for ISMIP6 (CMIP6)"

CMIP6 derived models

The source _id for these datasets below were derived from CMIP6 models so in the “comment” and “source” this needs to be changed from CMIP5 to CMIP6.


CESM2-ssp585-1-0

"source_id":" CESM2-ssp585-1-0”,

"comment":"This dataset was prepared using CMIP6 model CESM2 as input. A combination of historical and ssp585 datasets were used to create this forcing dataset for ISMIP6.",

"source":" CESM2-ssp585-1-0 derived dataset computed from CMIP5 CESM2 ssp585
and historical simulations",
"title":"Dataset derived from CESM2-ssp585-1-0  prepared for ISMIP6 (CMIP6)"


CNRM-CM6-1-ssp126-1-0

"source_id":" CNRM-CM6-1-ssp126-1-0”,

"comment":"This dataset was prepared using CMIP6 model CNRM-CM6-1 as input. A combination of historical and ssp126 datasets were used to create this forcing dataset for ISMIP6.",

"source":" CNRM-CM6-1-ssp126-1-0 derived dataset computed from CMIP5 CNRM-CM6-1 ssp126 and historical simulations",

"title":"Dataset derived from CNRM-CM6-1-ssp126-1-0 prepared for ISMIP6 (CMIP6)"


CNRM-CM6-1-ssp585-1-0

"source_id":" CNRM-CM6-1-ssp585-1-0”,

"comment":"This dataset was prepared using CMIP6 model CNRM-CM6-1 as input. A combination of historical and ssp585 datasets were used to create this forcing dataset for ISMIP6.",

"source":" CNRM-CM6-1-ssp585-1-0 derived dataset computed from CMIP5 CNRM-CM6-1 ssp585 and historical simulations",

"title":"Dataset derived from CNRM-CM6-1-ssp585-1-0 prepared for ISMIP6 (CMIP6)"


CNRM-ESM2-1-ssp585-1-0

"source_id":" CNRM-ESM2-1-ssp585-1-0”,

"comment":"This dataset was prepared using CMIP6 model CNRM-ESM2-1 as input. A combination of historical and ssp585 datasets were used to create this forcing dataset for ISMIP6.",

"source":" CNRM-ESM2-1-ssp585-1-0 derived dataset computed from CMIP5 CNRM-ESM2-1 ssp585 and historical simulations",

"title":"Dataset derived from CNRM-ESM2-1-ssp585-1-0 prepared for ISMIP6 (CMIP6)"


UKESM1-0-LL-ssp585-1-0

"source_id":" UKESM1-0-LL-ssp585-1-0”,

"comment":"This dataset was prepared using CMIP6 model UKESM1-0-LL as input. A combination of historical and ssp585 datasets were used to create this forcing dataset for ISMIP6.",

"source":" UKESM1-0-LL-ssp585-1-0 derived dataset computed from CMIP5 UKESM1-0-LL ssp585 and historical simulations",

"title":"Dataset derived from UKESM1-0-LL-ssp585-1-0 prepared for ISMIP6 (CMIP6)"


Thanks so much.
Please let me know if you need anything else.

**Comment by durack1** [comment]
Hi-jacking this issue to register the institution_id `NASA-GSFC`, with the following details. This institution is already registered a a modeling group contributor in the [CMIP6_CVs](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/master/CMIP6_institution_id.json#L34):

```python
"NASA-GSFC":"NASA Goddard Space Flight Center, Greenbelt, MD 20771, USA",
```
