### ISSUE TITLE
Generate new tables and variables for ISMIP6

### ISSUE THREAD

**Issue by durack1** [PCMDI/input4MIPs-cmor-tables#107]
@geresie that is the `mrros` variable see [here from the Lmon table](http://clipc-services.ceda.ac.uk/dreq/u/bab19ff8-e5dd-11e5-8482-ac72891c3257.html), whereas total runoff `mrro` is defined [here for the Lmon table](http://clipc-services.ceda.ac.uk/dreq/u/bab17a6e-e5dd-11e5-8482-ac72891c3257.html).

I will open a new issue to generate an `Lyr` table and make sure that `mrros` is included.

Which tables are you pulling the other variables from? I have guessed below, please correct anything wrong

"acabf" IyrGre/IyrAnt see [here for the IyrGre table](http://clipc-services.ceda.ac.uk/dreq/u/d5b3b1aa-c78d-11e6-9b25-5404a60d96b5.html)
"evspsbl" Amon see [here](http://clipc-services.ceda.ac.uk/dreq/u/baad45c0-e5dd-11e5-8482-ac72891c3257.html)
"mrros" Lmon see [here](http://clipc-services.ceda.ac.uk/dreq/u/bab19ff8-e5dd-11e5-8482-ac72891c3257.html)
"pr", Amon as for evspsbl
"sftflf" is this fixed or time invariant, in which case it would be the fx table
"so" Omon see [here](http://clipc-services.ceda.ac.uk/dreq/u/baa5491a-e5dd-11e5-8482-ac72891c3257.html)
"ts" Amon see [here](http://clipc-services.ceda.ac.uk/dreq/u/babaef0e-e5dd-11e5-8482-ac72891c3257.html)

Obviously if you are generating annual mean data, all these tables become annual/yearly: Ayr, Lyr, Oyr etc etc

_Originally posted by @durack1 in https://github.com/PCMDI/input4MIPs-cmor-tables/pull/106#issuecomment-663237254_

**Comment by durack1** [comment]
@geresie, just to clarify, all variables are annual/yearly right?

**Comment by durack1** [comment]
The following are required:

|table_id|exists?|variable_id|exists?|
|--|--|--|--|
|Ayr|nope|`evspsbl`|nope|
|Ayr|nope|`pr`|nope|
|Ayr|nope|`ts`|nope|
|LyrAnt|nope|`acabf`|nope|
|LyrGre|nope|`acabf`|nope|
|LIfx|yep|`sftflf`|nope|
|Lyr|nope|`mrros`|nope|
|Oyr|nope|`so`|nope|

**Comment by durack1** [comment]
@geresie, just checking that the above is correct? If this is accurate, then I will start on pulling across these tables/variables. Please do let me know if I have guessed a wrong table/realm above

**Comment by geresie** [comment]
Yes, these all seem to be correct. Thanks

**Comment by durack1** [comment]
@geresie those new tables/variables are now in place, feel free to pull these down, updating the existing `Tables` subdir, and using these to write your data

**Comment by geresie** [comment]
Thanks so much, Paul.

**Comment by durack1** [comment]
@geresie there were some changes with CMOR 3.6.0 (I think I mentioned this before, I have an issue opened #102), which means that if you have been using <3.6.0 and the demos in this repo to build your code base it may need a little tweak

**Comment by geresie** [comment]
Thanks Paul. I am using 3.6.0.

**Comment by durack1** [comment]
@geresie great, let me know if you hit any issues.

Once you have a working example, it'd be great to contribute this [as a demo](https://github.com/PCMDI/input4MIPs-cmor-tables/tree/master/demo), so others can pick up what you've developed
