### ISSUE TITLE
Create new A3hr table for JRA55-do OMIP dataset

### ISSUE THREAD

**Issue by durack1** [PCMDI/input4MIPs-cmor-tables#30]
The following variable mappings will be required, all residing in the `atmos` realm:

`q_10 = huss (with height coordinate values specified as 10m)` - [3hr](http://clipc-services.ceda.ac.uk/dreq/u/bab034a6-e5dd-11e5-8482-ac72891c3257.html)
`rain = pr` - [3hr](http://clipc-services.ceda.ac.uk/dreq/u/bab3c904-e5dd-11e5-8482-ac72891c3257.html)
`rlds = rlds` - [3hr](http://clipc-services.ceda.ac.uk/dreq/u/bab52b5a-e5dd-11e5-8482-ac72891c3257.html)
`rsds = rsds` - [3hr](http://clipc-services.ceda.ac.uk/dreq/u/bab5df78-e5dd-11e5-8482-ac72891c3257.html)
`slp = psl` - [3hr](http://clipc-services.ceda.ac.uk/dreq/u/8bb0d1c8-4a5b-11e6-9cd2-ac72891c3257.html) also `surface air pressure` - [3hr](http://clipc-services.ceda.ac.uk/dreq/u/bab47354-e5dd-11e5-8482-ac72891c3257.html)
`snow = prsn (or sbl?)` - [3hr](http://clipc-services.ceda.ac.uk/dreq/u/bab42912-e5dd-11e5-8482-ac72891c3257.html)
`t_10 = tas (with height coordinate values specified as 10m)` - [3hr](http://clipc-services.ceda.ac.uk/dreq/u/bab91b20-e5dd-11e5-8482-ac72891c3257.html)
`u_10 = uas` - [E3hr](http://clipc-services.ceda.ac.uk/dreq/u/7b1a301c-a220-11e6-a33f-ac72891c3257.html)
`v_10 = vas` - [E3hr](http://clipc-services.ceda.ac.uk/dreq/u/7b1a2c5c-a220-11e6-a33f-ac72891c3257.html)

In addition, an L3hr table may also be required for:
`runoff_all = ?` - [L3hr](http://clipc-services.ceda.ac.uk/dreq/u/bab177b2-e5dd-11e5-8482-ac72891c3257.html)

**Comment by HiroyukiTsujino** [comment]
Here is a list of temporal attributes for the 10 variables.

Following 9 variables can be found in 3hr or E3hr Table.
- q_10=huss, Instantaneous value, 3hr [0,3,6,9,12,15,18,21hr], height10m - 3hr
- rain=pr, Temporal mean, 3hr [1.5,4,5,7,5,10.5,13.5,16.5,19.5,22,5hr] - 3hr
- rlds=rlds, Temporal mean, 3hr [1.5,4,5,7,5,10.5,13.5,16.5,19.5,22,5hr]  - 3hr
- rsds=rsds, Temporal mean, 3hr [1.5,4,5,7,5,10.5,13.5,16.5,19.5,22,5hr]  - 3hr
- slp=psl, Instantaneous value, 3hr [0,3,6,9,12,15,18,21hr], - **E3hr**
- snow=prsn, Temporal mean, 3hr [1.5,4,5,7,5,10.5,13.5,16.5,19.5,22,5hr] - 3hr
- t_10=tas, Instantaneous value, 3hr [0,3,6,9,12,15,18,21hr], height10m - 3hr
- u_10=uas, **Instantaneous** value, 3hr [0,3,6,9,12,15,18,21hr], height10m - **3hr**
- v_10=vas, **Instantaneous** value, 3hr [0,3,6,9,12,15,18,21hr], height10m - **3hr**

Total daily mean runoff may be found in the the day Table, but it may be more appropriate to refer to friver in Omon table.
- runoff_all=mrro, Temporal mean, day, - day

or

- runoff_all=friver, Temporal mean, day -Oday? (currently not found Oday)

**Comment by durack1** [comment]
The following variable mappings will be required, all residing in the `atmos` and `ocean` realms:

Time mean - A3hr:
`rain = pr` - [3hr](http://clipc-services.ceda.ac.uk/dreq/u/bab3c904-e5dd-11e5-8482-ac72891c3257.html)
`rlds = rlds` - [3hr](http://clipc-services.ceda.ac.uk/dreq/u/bab52b5a-e5dd-11e5-8482-ac72891c3257.html)
`rsds = rsds` - [3hr](http://clipc-services.ceda.ac.uk/dreq/u/bab5df78-e5dd-11e5-8482-ac72891c3257.html)
`snow = prsn` - [3hr](http://clipc-services.ceda.ac.uk/dreq/u/bab42912-e5dd-11e5-8482-ac72891c3257.html)

Instantaneous - A3hrPt:
`q_10 = huss (with height coordinate values specified as 10m - 2m is default, will be overwritten with height value)` - [3hr](http://clipc-services.ceda.ac.uk/dreq/u/bab034a6-e5dd-11e5-8482-ac72891c3257.html)
`slp = psl` - [E3hr](http://clipc-services.ceda.ac.uk/dreq/u/8bb0d1c8-4a5b-11e6-9cd2-ac72891c3257.html)
`t_10 = tas (with height coordinate values specified as 10m - 2m is default, will be overwritten with height value)` - [3hr](http://clipc-services.ceda.ac.uk/dreq/u/bab91b20-e5dd-11e5-8482-ac72891c3257.html)
`u_10 = uas (with height coordinate values specified as 10m - default)` - [3hr](http://clipc-services.ceda.ac.uk/dreq/u/babb5db8-e5dd-11e5-8482-ac72891c3257.html)
`v_10 = vas  (with height coordinate values specified as 10m - default)` - [3hr](http://clipc-services.ceda.ac.uk/dreq/u/babbdec8-e5dd-11e5-8482-ac72891c3257.html)

Daily - Oday:
`runoff_all = friver` - [Oday](http://clipc-services.ceda.ac.uk/dreq/u/baa6247a-e5dd-11e5-8482-ac72891c3257.html)

**Comment by durack1** [comment]
@HiroyukiTsujino there has been a question raised about the salinity restoring fields for JRA55-do. The currently available data (http://amaterasu.ees.hokudai.ac.jp/~tsujino/JRA55-do-v1.3/) does not appear to include any salinity variables, so it would be useful to add this to the variable list to process when they do become available

**Comment by HiroyukiTsujino** [comment]
The salinity restoring fields for JRA55-do are actually available from [Supplemental data for JRA55-do](http://amaterasu.ees.hokudai.ac.jp/~tsujino/JRA55-do-suppl/woa13v2/).

They are based on WOA13v2 and the upper 10 m (0-10m) average of the monthly climatology of salinity.

- woa13_decav_s_0-10m.mon_01v2.nc ... the land-sea mask of WOA13 is used
- woa13_decav_s_0-10m,mon_01v2_filled.nc ... the land grids are filled using salinity values on the neighboring ocean grids.

Sea surface salinity can be found as "sos" in the Omon Table.

- s_u10a=sos, temporal mean, monthly climatology, at the nominal depth of 5 m - Omon (or Oclim?)

**Comment by durack1** [comment]
@HiroyukiTsujino thanks, I've now managed to pull all these variables across (see PCMDI/input4MIPs-cmor-tables#32) which now deals with all the variables required for the JRA55-do rewrite. I'll work on generating the demo script to call CMOR across these files tomorrow

**Comment by durack1** [comment]
@HiroyukiTsujino @StephenGriffies just to check, 10m winds are what I expect, but for surface flux calculations don’t we need 2m `tas` AND `huss` data (rather than 10m `huss`)?

**Comment by HiroyukiTsujino** [comment]
In OMIP, a sample code based on Large and Yeager (2009) for computing turbulent fluxes for heat and momentum is provided, and it assumes wind, air temperature (tas), and specific humidity (huss) **ALL** at 10 m. So we are OK with 10 m tas and huss as long as OMIP is concerned.
